const CONSTANTS = {};

/**
 * CONSTANTS ENDPOINTS
 */

CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";

CONSTANTS.ENDPOINT.COFFEESHOPS = "/coffeeshops";

CONSTANTS.ENDPOINT.GRID = "/grid";

CONSTANTS.ENDPOINT.ORDER = "/order";

CONSTANTS.ENDPOINT.LIST = "/list";

CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

module.exports = CONSTANTS;
