const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";
CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.ENDPOINT.LIST = "/list";

CONSTANTS.ENDPOINT.ORDER = "/order";

CONSTANTS.ENDPOINT.COFFEESHOPS = "/coffeeshops";

CONSTANTS.ENDPOINT.GRID = "/grid";

CONSTANTS.ENDPOINT.HOME = "/home";

module.exports = CONSTANTS;
